version: "3.8"
services:
  build-agent:
    image: build-agent:latest
    build:
      context: .
      dockerfile: ./build_agent/Dockerfile
  test-agent:
    image: test-agent:latest
    build:
      context: .
      dockerfile: ./test_agent/Dockerfile
    depends_on:
      - build-agent
